SELECT E.EMPLOYEE_ID,
       E.FIRST_NAME || '.' || E.LAST_NAME,
       E.HIRE_DATE,
       D.DEPARTMENT_NAME,
       E1.FIRST_NAME || '.' || E1.LAST_NAME MANAGER_NAME,
       L.STREER_ADDRESS£¬ L.CITY,
       L.STATE_PROVINCE
  FROM EMPLOYEES E, DEPARTMENTS D, EMPLOYEES E1, LOCATIONS L
 WHERE 1 = 1
   AND E.DEPARTMENT_ID = D.DEPARTMENT_ID
   AND E.MANAGER_ID = E1.EMPLOYEE_ID
   AND D.LOCATION_ID = L.LOCATION_ID
